import type { Dispatch } from "react";
import { Icon } from "../components/Icon";
import { CloseBar } from "../components/CloseBar";
import { NavBar } from "../components/NavBar";
import { STRINGS, t } from "../i18n";
import { daysUntil, fmtDate, isOverdue } from "../lib/dates";
import { areaItemDef, INSTITUTION_URLS } from "../lib/areaItems";
import type { AppState, Lang } from "../types";
import type { Action } from "../state/store";
import { KompasHome } from "./KompasHome";
import { Kompas } from "./Kompas";

const RESIDENCE_SOURCE = "https://www.gesetze-im-internet.de/aufenthg_2004/__81.html";
const MOVE_SOURCE = "https://www.gesetze-im-internet.de/bmg/__17.html";
const WORK_SOURCE = "https://www.gesetze-im-internet.de/aufenthg_2004/__4a.html";

type Guide = { label:string; title:string; intro:string; legal:string; legalText:string; steps:string[]; docs:string; docsText:string; planning:string; planningText:string; source:string; checked:string; sourceUrl:string };

function permitGuide(lang: Lang): Guide {
  if (lang === "de") return {label:"Schritt für Schritt",title:"Aufenthaltstitel verlängern",intro:"Wenn dein befristeter Aufenthaltstitel ausläuft, ist der entscheidende Punkt: Stelle den Antrag auf Verlängerung oder auf einen anderen Aufenthaltstitel vor dem Ablaufdatum.",legal:"Wichtig zum Fristdatum",legalText:"Nach § 81 Abs. 4 AufenthG gilt der bisherige Aufenthaltstitel grundsätzlich bis zur Entscheidung der Ausländerbehörde fort, wenn du die Verlängerung oder einen anderen Aufenthaltstitel vor Ablauf beantragst. Für Visa nach § 6 Abs. 1 gilt diese Regel nicht.",steps:["Prüfe das Ablaufdatum auf deinem aktuellen Aufenthaltstitel.","Prüfe die Website deiner zuständigen Ausländerbehörde: Antrag, Termin und Unterlagen unterscheiden sich lokal und nach Aufenthaltstitel.","Bereite die für deinen Aufenthaltstitel verlangten Nachweise vor.","Stelle den Antrag vor Ablauf deines aktuellen Aufenthaltstitels und bewahre den Nachweis der Antragstellung auf.","Reagiere auf Nachforderungen der Behörde und nimm einen erforderlichen Termin wahr."],docs:"Typische Unterlagen",docsText:"Häufig werden gültiger Pass, aktueller Aufenthaltstitel, biometrisches Foto und Nachweise zum Aufenthaltszweck verlangt. Die genaue Liste hängt von deinem Titel und deiner Ausländerbehörde ab.",planning:"Planung, nicht Gesetz",planningText:"Ausländerleben erinnert dich 8 Wochen vorher als Vorbereitungshilfe. Das ist kein allgemeiner gesetzlicher 8-Wochen-Termin. Entscheidend ist, den Antrag vor Ablauf zu stellen.",source:"Gesetzliche Grundlage öffnen",checked:"Inhalt geprüft: September 2026",sourceUrl:RESIDENCE_SOURCE};
  if (lang === "sr") return {label:"Korak po korak",title:"Produženje boravišne dozvole",intro:"Ako ti ističe vremenski ograničena boravišna dozvola, ključna stvar je da zahtev za produženje ili drugi boravišni status podneseš pre datuma isteka.",legal:"Važno za rok",legalText:"Prema § 81 st. 4 AufenthG, ako pre isteka zatražiš produženje ili drugi boravišni status, postojeći status u načelu nastavlja da važi do odluke Ausländerbehörde. Ovo pravilo ne važi za vize iz § 6 st. 1.",steps:["Proveri datum isteka na trenutnoj boravišnoj dozvoli.","Proveri sajt svoje Ausländerbehörde: način prijave, termin i dokumenta zavise od mesta i vrste dozvole.","Pripremi dokumenta koja se traže baš za tvoj tip boravka.","Podnesi zahtev pre isteka trenutne dozvole i sačuvaj dokaz da je zahtev podnet.","Odgovori na eventualne dodatne zahteve i pojavi se na terminu ako je potreban."],docs:"Tipična dokumenta",docsText:"Često se traže važeći pasoš, trenutna boravišna dozvola, biometrijska fotografija i dokazi vezani za svrhu boravka. Tačan spisak zavisi od dozvole i lokalne Ausländerbehörde.",planning:"Planiranje, ne zakonski rok",planningText:"Ausländerleben daje podsetnik 8 nedelja ranije kao pomoć za pripremu. To nije univerzalni zakonski rok od 8 nedelja. Ključno je da zahtev bude podnet pre isteka.",source:"Otvori zakonski izvor",checked:"Sadržaj proveren: septembar 2026",sourceUrl:RESIDENCE_SOURCE};
  return {label:"Step by step",title:"Renew your residence permit",intro:"If your temporary residence title is expiring, the key point is to submit the application for an extension or another residence title before the expiry date.",legal:"Important deadline rule",legalText:"Under Section 81(4) of the Residence Act, if you apply for an extension or another residence title before expiry, your existing title generally continues until the immigration authority decides. This rule does not apply to visas under Section 6(1).",steps:["Check the expiry date on your current residence title.","Check your local immigration authority's website: application method, appointment process and documents vary by location and residence title.","Prepare the evidence required for your specific residence purpose.","Submit the application before your current title expires and keep proof of submission.","Respond to requests for additional documents and attend an appointment if required."],docs:"Typical documents",docsText:"A valid passport, current residence title, biometric photo and evidence related to your residence purpose are commonly requested. The exact list depends on your title and local immigration authority.",planning:"Planning, not a legal deadline",planningText:"Ausländerleben gives you an 8-week preparation reminder. This is not a universal statutory 8-week deadline. The key legal safeguard is applying before expiry.",source:"Open legal source",checked:"Content checked: September 2026",sourceUrl:RESIDENCE_SOURCE};
}

function moveGuide(lang: Lang): Guide {
  if(lang==="de") return {label:"Schritt für Schritt",title:"Umziehen und Adresse anmelden",intro:"Nach dem Einzug in eine neue Wohnung gehört die Anmeldung bei der Meldebehörde zu den wichtigsten ersten Schritten.",legal:"Gesetzliche Frist",legalText:"§ 17 Abs. 1 BMG verlangt grundsätzlich die Anmeldung innerhalb von zwei Wochen nach dem Einzug. Entscheidend ist das tatsächliche Einzugsdatum – nicht das Datum deiner Einreise nach Deutschland.",steps:["Notiere dein tatsächliches Einzugsdatum in die neue Wohnung.","Besorge die Wohnungsgeberbestätigung von Vermieter oder Wohnungsgeber.","Prüfe das Verfahren deiner zuständigen Meldebehörde und buche bei Bedarf einen Termin.","Melde die neue Wohnung innerhalb der gesetzlichen Frist an.","Aktualisiere danach deine Adresse bei Stellen, die sie benötigen, zum Beispiel Bank, Versicherungen und gegebenenfalls Ausländerbehörde."],docs:"Typische Unterlagen",docsText:"Typischerweise brauchst du ein Identitätsdokument und die Wohnungsgeberbestätigung. Kommunen können weitere Angaben oder Unterlagen verlangen.",planning:"Wichtig",planningText:"Ausländerleben berechnet diese Frist nur, wenn ein echtes Einzugsdatum vorliegt. Das Einreisedatum nach Deutschland wird dafür nicht verwendet.",source:"§ 17 BMG öffnen",checked:"Inhalt geprüft: September 2026",sourceUrl:MOVE_SOURCE};
  if(lang==="sr") return {label:"Korak po korak",title:"Selidba i prijava nove adrese",intro:"Nakon useljenja u novi stan, prijava adrese kod Meldebehörde je jedan od najvažnijih prvih koraka.",legal:"Zakonski rok",legalText:"§ 17 st. 1 BMG u načelu zahteva Anmeldung u roku od dve nedelje od useljenja. Bitan je stvarni datum useljenja u stan — ne datum dolaska u Nemačku.",steps:["Zapiši stvarni datum useljenja u novi stan.","Uzmi Wohnungsgeberbestätigung od stanodavca ili osobe koja ti daje stan na korišćenje.","Proveri proceduru svoje Meldebehörde i zakaži termin ako je potreban.","Prijavi novu adresu u zakonskom roku.","Posle toga ažuriraj adresu kod institucija kojima je potrebna, npr. banka, osiguranje i po potrebi Ausländerbehörde."],docs:"Tipična dokumenta",docsText:"Tipično su potrebni identifikacioni dokument i Wohnungsgeberbestätigung. Lokalna uprava može tražiti dodatne podatke ili dokumenta.",planning:"Važno",planningText:"Ausländerleben će računati ovaj rok samo kada imamo stvarni datum useljenja. Datum dolaska u Nemačku ne koristimo kao zamenu.",source:"Otvori § 17 BMG",checked:"Sadržaj proveren: septembar 2026",sourceUrl:MOVE_SOURCE};
  return {label:"Step by step",title:"Move and register your new address",intro:"After moving into a new home, registering the address with the registration authority is one of the key first steps.",legal:"Statutory deadline",legalText:"Section 17(1) BMG generally requires registration within two weeks after moving into the dwelling. The relevant date is the actual move-in date — not your arrival date in Germany.",steps:["Record the actual date you moved into the new home.","Get the Wohnungsgeberbestätigung from your landlord or housing provider.","Check the procedure of your responsible registration authority and book an appointment if required.","Register the new address within the statutory period.","Then update your address with organisations that need it, such as your bank, insurers and, where relevant, the immigration authority."],docs:"Typical documents",docsText:"An identity document and Wohnungsgeberbestätigung are typically needed. Local authorities may require additional information or documents.",planning:"Important",planningText:"Ausländerleben will only calculate this deadline when an actual move-in date is available. We do not use your arrival date in Germany as a substitute.",source:"Open Section 17 BMG",checked:"Content checked: September 2026",sourceUrl:MOVE_SOURCE};
}

function jobGuide(lang: Lang): Guide {
  if(lang==="de") return {label:"Schritt für Schritt",title:"Arbeitgeber wechseln",intro:"Ob du einen neuen Job direkt beginnen darfst, hängt von deinem Aufenthaltstitel und möglichen Beschränkungen zur Beschäftigung ab.",legal:"Vor dem Jobwechsel prüfen",legalText:"Nach § 4a AufenthG muss jeder Aufenthaltstitel erkennen lassen, ob Erwerbstätigkeit erlaubt und ob sie beschränkt ist. Wurde der Titel für eine bestimmte Beschäftigung erteilt, darf eine andere Beschäftigung nicht ausgeübt werden, solange die zuständige Behörde sie nicht erlaubt hat.",steps:["Prüfe Aufenthaltstitel und Zusatzblatt auf Hinweise zur Erwerbstätigkeit oder Arbeitgeberbindung.","Vergleiche neuen Job und Arbeitgeber mit den dort genannten Beschränkungen.","Wenn eine Beschränkung geändert werden muss, kläre dies vor Arbeitsbeginn mit der zuständigen Ausländerbehörde.","Bereite neuen Arbeitsvertrag bzw. verbindliches Jobangebot und weitere verlangte Nachweise vor.","Beginne die neue Beschäftigung erst, wenn dein Titel sie erlaubt oder die erforderliche Erlaubnis vorliegt."],docs:"Typische Unterlagen",docsText:"Je nach Aufenthaltstitel können Pass, Aufenthaltstitel/Zusatzblatt, neuer Arbeitsvertrag oder Jobangebot und Angaben zur Beschäftigung relevant sein. Die Anforderungen unterscheiden sich nach Titel und Behörde.",planning:"Nicht pauschalisieren",planningText:"Ein Arbeitgeberwechsel ist nicht bei jedem Aufenthaltstitel gleich geregelt. Ausländerleben zeigt deshalb keine pauschale Aussage wie „immer erlaubt“ oder „immer genehmigungspflichtig“.",source:"§ 4a AufenthG öffnen",checked:"Inhalt geprüft: September 2026",sourceUrl:WORK_SOURCE};
  if(lang==="sr") return {label:"Korak po korak",title:"Promena poslodavca",intro:"Da li možeš odmah da počneš novi posao zavisi od tvoje boravišne dozvole i eventualnih ograničenja za zaposlenje.",legal:"Proveri pre promene posla",legalText:"Prema § 4a AufenthG, na boravišnoj dozvoli mora biti vidljivo da li je rad dozvoljen i da li postoje ograničenja. Ako je dozvola izdata za određeno zaposlenje, drugačije zaposlenje nije dozvoljeno dok nadležni organ ne odobri promenu, kada je takvo odobrenje potrebno.",steps:["Proveri Aufenthaltstitel i Zusatzblatt i potraži napomene o radu ili vezanosti za poslodavca.","Uporedi novi posao i poslodavca sa navedenim ograničenjima.","Ako ograničenje mora da se promeni, reši to sa Ausländerbehörde pre početka novog posla.","Pripremi novi ugovor ili obavezujuću ponudu za posao i druge tražene dokaze.","Počni novi posao tek kada tvoja dozvola to omogućava ili kada dobiješ potrebno odobrenje."],docs:"Tipična dokumenta",docsText:"U zavisnosti od dozvole mogu biti relevantni pasoš, Aufenthaltstitel/Zusatzblatt, novi ugovor ili ponuda i podaci o zaposlenju. Zahtevi zavise od vrste dozvole i nadležnog organa.",planning:"Bez univerzalnog pravila",planningText:"Promena poslodavca nije ista za svaku boravišnu dozvolu. Zato Ausländerleben neće tvrditi da je promena uvek slobodna niti da je uvek potrebno odobrenje.",source:"Otvori § 4a AufenthG",checked:"Sadržaj proveren: septembar 2026",sourceUrl:WORK_SOURCE};
  return {label:"Step by step",title:"Change employers",intro:"Whether you can start a new job immediately depends on your residence title and any employment restrictions attached to it.",legal:"Check before changing jobs",legalText:"Under Section 4a of the Residence Act, every residence title must show whether employment is permitted and whether restrictions apply. If a title was issued for a specific employment, another employment may not be taken up unless the competent authority permits it where such permission is required.",steps:["Check your residence title and Zusatzblatt for employment conditions or an employer restriction.","Compare the new job and employer with those conditions.","If a restriction needs to be changed, clarify this with the immigration authority before starting the new job.","Prepare the new employment contract or binding job offer and any other requested evidence.","Start the new employment only when your title allows it or the required permission has been granted."],docs:"Typical documents",docsText:"Depending on the residence title, your passport, residence title/Zusatzblatt, new employment contract or job offer and employment details may be relevant. Requirements vary by title and authority.",planning:"No one-size-fits-all rule",planningText:"Employer changes are not treated identically under every residence title. Ausländerleben therefore avoids blanket claims that a change is always free or always requires approval.",source:"Open Section 4a Residence Act",checked:"Content checked: September 2026",sourceUrl:WORK_SOURCE};
}

function guideFor(id:string,lang:Lang):Guide|null { if(id==="boravak_permit") return permitGuide(lang); if(id==="boravak_anmeldung") return moveGuide(lang); if(id==="rad_contract") return jobGuide(lang); return null; }

export function AreaItemDetail({ state, dispatch }: { state: AppState; dispatch: Dispatch<Action> }) {
  const S=STRINGS[state.lang!]; if(!state.profile) return <KompasHome state={state} dispatch={dispatch}/>;
  const def=areaItemDef(state.selectedAreaItem); const text=def?S.extra[def.id]:null; if(!def||!text){dispatch({type:"NAV",view:"kompas"});return <Kompas state={state} dispatch={dispatch}/>;}
  const deadline=def.kind==="obligation"&&def.deadline?def.deadline(state.profile):null; let deadlineBlock:React.ReactNode=null;
  if(def.kind==="obligation"){if(deadline){const overdue=isOverdue(deadline);deadlineBlock=<div className="card" style={{padding:16,display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,...(overdue?{borderColor:"var(--accent)"}:{})}}><div><div className="mono" style={{fontSize:11,color:"var(--ink-faint)",textTransform:"uppercase"}}>{S.rokovi.tagObligation}</div><div style={{fontWeight:600,fontSize:14,marginTop:2}}>{fmtDate(deadline,state.lang!)}</div></div><span className={"pill "+(overdue?"pill-warn":"pill-info")}>{overdue?S.rokovi.overdue:t(S.rokovi.pill,{d:daysUntil(deadline)})}</span></div>}else deadlineBlock=<div className="card" style={{padding:16,fontSize:13,color:"var(--ink-soft)"}}>{S.kompas.noDateYet}</div>}
  const url=INSTITUTION_URLS[def.id]; const guide=guideFor(def.id,state.lang!);
  return <><div className="screen"><CloseBar onClose={()=>dispatch({type:"NAV",view:"objasnjeno"})}/><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:46,height:46,borderRadius:"6px 16px 6px 6px",background:"var(--primary-soft)",display:"flex",alignItems:"center",justifyContent:"center",flex:"none",color:"var(--primary)"}}><Icon name={def.icon} size={22}/></div><div><div className="disp" style={{fontSize:19,fontWeight:700}}>{guide?.title??text.name}</div><span className={"pill "+(def.kind==="obligation"?"pill-warn":"pill-info")} style={{marginTop:3}}>{guide?.label??(def.kind==="obligation"?S.rokovi.tagObligation:S.rokovi.tagRight)}</span></div></div>
  {guide?<><div className="card" style={{padding:16,fontSize:14,lineHeight:1.6}}>{guide.intro}</div><div className="card" style={{padding:16,borderColor:"var(--primary)"}}><div className="eyebrow">{guide.legal}</div><p style={{fontSize:13.5,lineHeight:1.6,margin:"8px 0 0"}}>{guide.legalText}</p></div><section><div className="eyebrow" style={{marginBottom:9}}>{guide.label}</div><div style={{display:"flex",flexDirection:"column",gap:9}}>{guide.steps.map((step,i)=><div className="card" key={step} style={{padding:14,display:"flex",gap:12,alignItems:"flex-start"}}><span className="pill pill-info" style={{flex:"none"}}>{i+1}</span><span style={{fontSize:13.5,lineHeight:1.5}}>{step}</span></div>)}</div></section><div className="card" style={{padding:16}}><strong style={{fontSize:13.5}}>{guide.docs}</strong><p style={{fontSize:13,lineHeight:1.55,color:"var(--ink-soft)",margin:"6px 0 0"}}>{guide.docsText}</p></div><div className="card" style={{padding:16,background:"var(--surface-2)"}}><strong style={{fontSize:13.5}}>{guide.planning}</strong><p style={{fontSize:13,lineHeight:1.55,color:"var(--ink-soft)",margin:"6px 0 0"}}>{guide.planningText}</p></div><a href={guide.sourceUrl} target="_blank" rel="noopener noreferrer" className="card" style={{padding:"12px 14px",display:"flex",alignItems:"center",justifyContent:"space-between",textDecoration:"none",color:"inherit"}}><span style={{fontSize:13.5,fontWeight:600,color:"var(--primary)"}}>{guide.source}</span><Icon name="external" size={16}/></a><div style={{fontSize:11.5,color:"var(--ink-faint)"}}>{guide.checked}</div></>:<><div className="card" style={{padding:16,fontSize:14,lineHeight:1.6}}>{text.desc}</div>{text.consequence&&<div className="card" style={{padding:16,fontSize:13.5,lineHeight:1.6,color:"var(--ink-soft)"}}>{text.consequence}</div>}{deadlineBlock}{url&&<a href={url} target="_blank" rel="noopener noreferrer" className="card" style={{padding:"12px 14px",display:"flex",alignItems:"center",justifyContent:"space-between",textDecoration:"none",color:"inherit"}}><span style={{fontSize:13.5,fontWeight:600,color:"var(--primary)"}}>{S.benefit.openLink}</span><Icon name="external" size={16}/></a>}</>}<div style={{flex:1}}/><div style={{fontSize:11.5,color:"var(--ink-faint)",lineHeight:1.5,paddingBottom:28}}>{S.benefit.disclaimer}</div></div><NavBar active={null} lang={state.lang!} onNav={(view)=>dispatch({type:"NAV",view})}/></>;
}
